enum GameState {
    WAITING_FOR_CUT = "WAITING_FOR_CUT",
    WAITING_FOR_BET = "WAITING_FOR_BET",
    WAITING_FOR_DECISION = "WAITING_FOR_DECISION",
    DEALER_TURN = "DEALER_TURN",
    ROUND_END = "ROUND_END",
}

enum ErrorCode {
    ERR_SESSION_NOT_FOUND = "ERR_SESSION_NOT_FOUND",
    ERR_INVALID_STATE = "ERR_INVALID_STATE",
    ERR_INSUFFICIENT_FUNDS = "ERR_INSUFFICIENT_FUNDS",
    ERR_INVALID_AMOUNT = "ERR_INVALID_AMOUNT",
}
export { GameState, ErrorCode };
